### ISSUE TITLE
Message is misleading

### ISSUE THREAD

**Issue by ufechner7** [ufechner7/PkgHelpers.jl#11]
If I have existing compat entries, and execute
```
using Pkg, PkgHelpers
freeze(Pkg)
```
I get the message:
```
Added 25 entries to the compat section!
```
But this is not true. The file "Project.toml" did not change.

So please:
- either print no message
- or print correct messages, e.g.
```
Kept 25 entries in compat section unchanged.
```

**Comment by KeithWM** [comment]
Is the message necessary at all? I did also spot this at some point, but then (conventiently but not deliberately) forgot about it later. I think it might be a lot of hassle to maintain something that is very explicit about exactly what has been done, especially if functionality is at some point extended. Maybe "Compat section now has 25 entries (was 12)." would be sufficient.

**Comment by ufechner7** [comment]
> Maybe "Compat section now has 25 entries (was 12)." would be sufficient.

Sounds good to me!
