### ISSUE TITLE
Add option to keep existing compat entries

### ISSUE THREAD

**Issue by ufechner7** [ufechner7/PkgHelpers.jl#5]
Sometimes you might want to keep existing compat entries, e.g. if you tested that two different sets of package versions work well with your project.

**Comment by KeithWM** [comment]
This is exactly what I wanted to try. Why is the TOML not just written using TOML library functionality? That seems to make everything a lot more complicated.

```julia
    toml_data = TOML.parsefile(toml_file)
     ...
    open(toml_file, "w") do toml_io
        TOML.print(toml_io, toml_data)
    end
```

**Comment by KeithWM** [comment]
As a side note, I would also suggest using the caret `^` explicitly. I don't find it _that_ intuitive that the default `Dep = "1.2"` is implicitly `Dep = "^1.2"`, especially for novice users (coming from Python?) it looks like it is `Dep = "=1.2"`.

**Comment by ufechner7** [comment]
> As a side note, I would also suggest using the caret `^` explicitly. I don't find it _that_ intuitive that the default `Dep = "1.2"` is implicitly `Dep = "^1.2"`, especially for novice users (coming from Python?) it looks like it is `Dep = "=1.2"`.

I do not understand this comment. To which parameter of which function do you refer to?

**Comment by KeithWM** [comment]
This comment is about the form of the `compat` entry. In Julia, if only a version is specified, this is interpreted the same as if it were given with a caret (`^`). To me, it seems like it would be nicer to people starting with the language (or looking at compats for the first time) to be explicit that a version specifier is not a strict bound, but a semantic versioning compatibility. I believe adding the caret symbol makes this more explicit.

**Comment by ufechner7** [comment]
> This comment is about the form of the `compat` entry. In Julia, if only a version is specified, this is interpreted the same as if it were given with a caret (`^`). To me, it seems like it would be nicer to people starting with the language (or looking at compats for the first time) to be explicit that a version specifier is not a strict bound, but a semantic versioning compatibility. I believe adding the caret symbol makes this more explicit.

If this shall be an actionable item, please create a new issue for it.

**Comment by ufechner7** [comment]
Closed by https://github.com/ufechner7/PkgHelpers.jl/pull/9
